# Generated by Django 2.2.3 on 2019-07-18 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(max_length=64)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_status', models.BooleanField(default=True)),
                ('user_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=64)),
                ('recipe_description', models.CharField(max_length=1024)),
                ('recipe_ingredients', models.TextField(default='Вводите через запятую')),
                ('recipe_steps', models.TextField()),
                ('recipe_photo', models.ImageField(upload_to='media/upload/')),
                ('recipe_type_of_meal', models.CharField(choices=[('salad', 'Салат'), ('soup', 'Суп'), ('first', 'Первое'), ('second', 'Второе'), ('dessert', 'Десерт'), ('drinks', 'Напиток')], default='salad', max_length=128)),
                ('recipe_status', models.BooleanField(default=True)),
                ('recipe_likes', models.IntegerField(default=0)),
                ('recipe_created', models.DateTimeField(auto_now_add=True)),
                ('recipe_update', models.DateTimeField(auto_now=True)),
                ('recipe_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.User')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'db_table': 'recipe',
            },
        ),
    ]
